---
- name: Add repository CentOS6
  yum: 
    name: https://repo.zabbix.com/zabbix/3.4/rhel/6/x86_64/zabbix-release-3.4-1.el6.noarch.rpm
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_version < "7"

- name: Add repository CentOS7
  yum: 
    name: https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_version >= "7"